# Generated by Django 5.1 on 2024-09-12 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('county', models.CharField(choices=[('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana_river', 'Tana River'), ('lamu', 'Lamu'), ('taita_taveta', 'Taita Taveta'), ('garissa', 'Garissa'), ('wajir', 'Wajir'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('meru', 'Meru'), ('tharaka_nithi', 'Tharaka Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'), ('murang_a', 'Muranga'), ('kiambu', 'Kiambu'), ('turkana', 'Turkana'), ('west_pokot', 'West Pokot'), ('samburu', 'Samburu'), ('trans_nzoia', 'Trans Nzoia'), ('uasin_gishu', 'Uasin Gishu'), ('elgeyo_marakwet', 'Elgeyo Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'), ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homabay', 'Homa Bay'), ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira'), ('nairobi', 'Nairobi')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
